spring.application.name=QuantityMeasurementApp
server.port=8080

# Repository Type Configuration either "cache" or "database"
repository.type=database

# JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# MySQL
spring.datasource.url={SPRING_DATASOURCE_URL}
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username={SPRING_DATASOURCE_USERNAME}
spring.datasource.password={SPRING_DATASOURCE_PASSWORD}

# Connection Pool
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000

# Swagger/OpenAPI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true

# Actuator
management.endpoints.web.exposure.include=health,metrics,info
management.endpoint.health.show-details=always
management.endpoint.metrics.enabled=true
